import React, {useState, useEffect} from 'react'
import {Card, FormField, Loader} from '../components';

const RenderCards = ({data, title})=>{
  if(data?.length > 0) return data.map((post) => <Card key={post._id} {...post}/>)
  return (
    <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>{title}</h2>
  )
}

function Home() {
  const [loading, setloading] = useState(false);
  const [allposts, setallposts] = useState(null);
  const [searchtext, setsearchtext] = useState('');
  const [searchresults, setsearchresults] = useState(null);
  const [searchtimeout, setsearchtimeout] = useState(null);
  const handlsearch = (e) => {
    clearTimeout(searchtimeout);
    setsearchtext(e.target.value);
    setsearchtimeout(
      setTimeout(() => {
        const searchres = allposts.filter(item => item.name.toLowerCase().includes(searchtext.toLowerCase())
        || item.prompt.toLowerCase().includes(searchtext.toLowerCase()));
        setsearchresults(searchres);
      }, 1000)
    )
  }
  useEffect(() => {
    const fetchposts = async () => {
      setloading(true);
      try{
        const res = await fetch("http://localhost:5000/api/v1/post", {
          method: 'GET',
          headers: {
            'Content-Type' : 'application/json'
          }
        })
        if(res.ok){
          const result = await res.json();
          setallposts(result.data.reverse());
        }
      }catch(err){
        alert(err);
      }finally{
        setloading(false);
      }
    }
    fetchposts();
  }, [])
  return (
    <section className='mx-auto w-full'>
      <div>
        <h1 className='text-[32px] font-extrabold text-[#222328]'>The Community showcase</h1>
        <p className='mt-2 text-[#666e75] text-[16px]'>
          Browse through a collection of imaginative and visually stunning images generated by DALL-E API
        </p>
      </div>
      <div className='mx-auto mt-16 w-full sm:w-[75%] lg:w-[40%]'>
        <FormField
          labelname='Search Posts'
          type='text'
          name = 'text'
          placeholder='Search Posts'
          value={searchtext}
          handlechange={handlsearch}/>
      </div>
      <div className='mt-10'>
        {
          loading ? (
            <div className='flex justify-center items-center'>
              <Loader/>
            </div>
          ) : (
            <>
            {
              searchtext && (
                <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                  Showing results for <span className='text-[#222328]'>{searchtext}</span>
                </h2>
              )
            }
            <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3 '>
              {
                searchtext ? (
                  <RenderCards data = {searchresults} title = "No results found"/>
                ) : (
                  <RenderCards data = {allposts} title = "No posts found"/>
                )
              }
            </div>
            </>
          )
        }
      </div>
    </section>
  )
}

export default Home
